[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd app && npm install"]

[phases.build]
cmds = [
  "cd app && npm run build",
  "cp -r app/public app/.next/standalone/public",
  "cp -r app/.next/static app/.next/standalone/.next/static"
]

[start]
cmd = "HOSTNAME=0.0.0.0 node app/.next/standalone/server.js"
